#Requires -Version 5.1
<#
.SYNOPSIS
  Install gbr-agent as a NON-INTERACTIVE Windows runner (WinSW service or S4U task).

.DESCRIPTION
  Safer minimal path for PC1 / production Windows hosts:

  1) Prefer WinSW (real Windows Service) when gbr-agent-service.exe sits next to
     the LocalAppData binary (Session 0 — inject stays halted by default).
  2) Else register Scheduled Task \GrokBuildRemoteAgentService with
     LogonType=S4U + RunLevel=HighestAvailable (NOT InteractiveToken).

  Defaults (David must explicitly clear halt for live inject):
    - Binary:  %LOCALAPPDATA%\GrokBuildRemote\gbr-agent.exe  (0.6.3+)
    - Env:     GBR_INJECT_HALT=1  (User scope) + -inject-halt flag
    - Logs:    C:\pc-build\gbr-agent-out\  via GBR_LOG_DIR (User scope)
    - One agent: MultipleInstancesPolicy=IgnoreNew; agent singleton lock

  Does NOT start the agent unless -Start is passed.
  Disables (does NOT delete) the legacy interactive task \GrokBuildRemoteAgent.
  Deletion of that legacy task requires David yes.

.PARAMETER Start
  Start the service/task after install. Default: off.

.PARAMETER SkipDisableInteractiveTask
  Leave the legacy Interactive-only \GrokBuildRemoteAgent task enabled.

.PARAMETER AllowInject
  Do not set GBR_INJECT_HALT / -inject-halt. David live-trial only.

.PARAMETER BinaryPath
  Override agent exe. Default: %LOCALAPPDATA%\GrokBuildRemote\gbr-agent.exe

.PARAMETER LogDir
  Override log directory. Default: C:\pc-build\gbr-agent-out

.NOTES
  Product: Grok Build Remote | LinespottingOrg
  No secrets. Interactive-only Task Scheduler mode is forbidden.
  Does not drive approval UI. Does not enable inject by default.
#>
[CmdletBinding()]
param(
  [switch]$Start,
  [switch]$SkipDisableInteractiveTask,
  [switch]$AllowInject,
  [string]$BinaryPath = "",
  [string]$LogDir = "C:\pc-build\gbr-agent-out"
)

$ErrorActionPreference = "Stop"
$TaskServiceName = "GrokBuildRemoteAgentService"
$LegacyInteractiveTask = "GrokBuildRemoteAgent"
$WinSWServiceId = "gbr-agent"

function Test-IsAdmin {
  $id = [Security.Principal.WindowsIdentity]::GetCurrent()
  $p = New-Object Security.Principal.WindowsPrincipal($id)
  return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Resolve-AgentBinary {
  param([string]$Override)
  if ($Override -and (Test-Path -LiteralPath $Override)) {
    return (Resolve-Path -LiteralPath $Override).Path
  }
  $default = Join-Path $env:LOCALAPPDATA "GrokBuildRemote\gbr-agent.exe"
  if (-not (Test-Path -LiteralPath $default)) {
    throw @"
gbr-agent.exe not found at:
  $default
Install/copy the 0.6.3+ binary to %LOCALAPPDATA%\GrokBuildRemote\gbr-agent.exe
(do not point the service at .aiprojects\gbr\agents\dist).
"@
  }
  return (Resolve-Path -LiteralPath $default).Path
}

function New-LogDirectory {
  param([string]$Dir)
  New-Item -ItemType Directory -Force -Path $Dir | Out-Null
  $probe = Join-Path $Dir ".gbr-write-probe"
  Set-Content -LiteralPath $probe -Value (Get-Date).ToString("o") -Encoding ascii
  Remove-Item -LiteralPath $probe -Force
}

function Set-HaltAndLogEnv {
  param([string]$LogDirectory, [bool]$HaltInject)
  # User-scope so S4U/logon runners inherit without InteractiveToken desktop.
  # David clears halt explicitly: setx GBR_INJECT_HALT 0  OR System Properties → delete.
  [Environment]::SetEnvironmentVariable("GBR_LOG_DIR", $LogDirectory, "User")
  $env:GBR_LOG_DIR = $LogDirectory
  if ($HaltInject) {
    [Environment]::SetEnvironmentVariable("GBR_INJECT_HALT", "1", "User")
    $env:GBR_INJECT_HALT = "1"
    Write-Host "Set User env GBR_INJECT_HALT=1 and GBR_LOG_DIR=$LogDirectory" -ForegroundColor Cyan
  } else {
    [Environment]::SetEnvironmentVariable("GBR_INJECT_HALT", $null, "User")
    Remove-Item Env:GBR_INJECT_HALT -ErrorAction SilentlyContinue
    Write-Host "AllowInject: cleared User env GBR_INJECT_HALT; GBR_LOG_DIR=$LogDirectory" -ForegroundColor Yellow
  }
}

function Install-WinSW {
  param(
    [string]$InstallDir,
    [string]$Exe,
    [string]$LogDirectory,
    [bool]$HaltInject,
    [bool]$DoStart
  )
  $winsw = Join-Path $InstallDir "gbr-agent-service.exe"
  if (-not (Test-Path -LiteralPath $winsw)) { return $false }

  $xmlPath = Join-Path $InstallDir "gbr-agent.xml"
  $haltEnv = if ($HaltInject) {
    '  <env name="GBR_INJECT_HALT" value="1"/>'
  } else {
    '  <!-- GBR_INJECT_HALT omitted (-AllowInject) -->'
  }
  $arguments = if ($HaltInject) { "-log=info -inject-halt run" } else { "-log=info run" }
  $xml = @"
<!-- Generated by scripts/windows/install-service.ps1 — no secrets -->
<service>
  <id>$WinSWServiceId</id>
  <name>Grok Build Remote Agent</name>
  <description>Grok Build Remote agent (non-interactive). Inject halted by default (GBR_INJECT_HALT=1).</description>
  <executable>$Exe</executable>
  <arguments>$arguments</arguments>
  <workingdirectory>$InstallDir</workingdirectory>
  <onfailure action="restart" delay="5 sec"/>
  <onfailure action="restart" delay="10 sec"/>
  <onfailure action="restart" delay="30 sec"/>
  <resetfailure>1 hour</resetfailure>
  <startmode>Automatic</startmode>
  <stoptimeout>15 sec</stoptimeout>
  <priority>Normal</priority>
  <logpath>$LogDirectory</logpath>
  <log mode="roll-by-size">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>8</keepFiles>
  </log>
  <env name="GBR_LOG_DIR" value="$LogDirectory"/>
$haltEnv
</service>
"@
  Set-Content -LiteralPath $xmlPath -Value $xml -Encoding UTF8

  & $winsw stop 2>$null | Out-Null
  & $winsw uninstall 2>$null | Out-Null
  $installOut = & $winsw install 2>&1
  if ($LASTEXITCODE -ne 0) {
    throw "WinSW install failed: $installOut"
  }
  Write-Host "Installed Windows Service via WinSW (id=$WinSWServiceId)." -ForegroundColor Green
  if ($DoStart) {
    & $winsw start
    Write-Host "Started WinSW service." -ForegroundColor Yellow
  } else {
    Write-Host "Service registered but NOT started (pass -Start to start)." -ForegroundColor Cyan
  }
  return $true
}

function Install-S4UTask {
  param(
    [string]$Exe,
    [bool]$HaltInject,
    [bool]$DoStart
  )
  if (-not (Test-IsAdmin)) {
    throw "S4U / Highest scheduled task requires an elevated PowerShell (Run as administrator)."
  }

  $userId = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
  $userXml = [System.Security.SecurityElement]::Escape($userId)
  $exeXml = [System.Security.SecurityElement]::Escape($Exe)
  $workXml = [System.Security.SecurityElement]::Escape((Split-Path -Parent $Exe))
  $argXml = if ($HaltInject) {
    "-log=info -inject-halt run"
  } else {
    "-log=info run"
  }

  # Direct Exec of gbr-agent.exe — one agent process (no interactive powershell host UI).
  # LogonType=S4U: non-interactive (InteractiveToken / Interactive-only FORBIDDEN).
  # RunLevel=HighestAvailable: Highest privileges without stealing desktop focus.
  $xml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Grok Build Remote agent — NON-INTERACTIVE (S4U+Highest). InteractiveToken forbidden. GBR_INJECT_HALT default.</Description>
    <URI>\$TaskServiceName</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>$userXml</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>$userXml</UserId>
      <LogonType>S4U</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>true</Hidden>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>$exeXml</Command>
      <Arguments>$argXml</Arguments>
      <WorkingDirectory>$workXml</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"@

  $tmp = Join-Path $env:TEMP "gbr-agent-ni-task.xml"
  $utf16 = New-Object System.Text.UnicodeEncoding $false, $true
  [System.IO.File]::WriteAllBytes($tmp, $utf16.GetPreamble() + $utf16.GetBytes($xml))

  # Distinct task name — never /F-overwrite legacy \GrokBuildRemoteAgent.
  schtasks.exe /Delete /TN $TaskServiceName /F 2>$null | Out-Null
  $create = schtasks.exe /Create /TN $TaskServiceName /XML $tmp /F 2>&1
  if ($LASTEXITCODE -ne 0) {
    throw "schtasks create failed: $create"
  }
  Write-Host "Registered non-interactive task \$TaskServiceName (S4U + Highest)." -ForegroundColor Green
  Write-Host "InteractiveToken / Interactive-only is FORBIDDEN for this runner." -ForegroundColor Yellow

  if ($DoStart) {
    schtasks.exe /Run /TN $TaskServiceName | Out-Null
    Write-Host "Started task \$TaskServiceName." -ForegroundColor Yellow
  } else {
    Write-Host "Task registered but NOT started (pass -Start to start)." -ForegroundColor Cyan
  }
}

function Disable-LegacyInteractiveTask {
  $null = schtasks.exe /Query /TN $LegacyInteractiveTask 2>&1
  if ($LASTEXITCODE -ne 0) {
    Write-Host "Legacy task \$LegacyInteractiveTask not present — nothing to disable." -ForegroundColor DarkGray
    return
  }
  schtasks.exe /Change /TN $LegacyInteractiveTask /DISABLE | Out-Null
  Write-Host "Disabled legacy interactive task \$LegacyInteractiveTask (NOT deleted; David must approve delete)." -ForegroundColor Yellow
}

# --- main ---
Write-Host "Grok Build Remote — non-interactive Windows install" -ForegroundColor Green
if ($AllowInject) {
  Write-Host "WARNING: -AllowInject set — GBR_INJECT_HALT will NOT be applied. David live trial only." -ForegroundColor Red
}

$exe = Resolve-AgentBinary -Override $BinaryPath
$installDir = Split-Path -Parent $exe
Write-Host "Binary: $exe"
New-LogDirectory -Dir $LogDir
Write-Host "Log dir: $LogDir"

$halt = -not $AllowInject.IsPresent
Set-HaltAndLogEnv -LogDirectory $LogDir -HaltInject $halt

$usedWinSW = Install-WinSW -InstallDir $installDir -Exe $exe -LogDirectory $LogDir -HaltInject $halt -DoStart:$Start.IsPresent
if (-not $usedWinSW) {
  Write-Host "WinSW (gbr-agent-service.exe) not found beside binary — using S4U scheduled task." -ForegroundColor Cyan
  Install-S4UTask -Exe $exe -HaltInject $halt -DoStart:$Start.IsPresent
}

if (-not $SkipDisableInteractiveTask.IsPresent) {
  Disable-LegacyInteractiveTask
}

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "  Halt default:  GBR_INJECT_HALT=$([int]$halt)  (David clears explicitly for live inject)"
Write-Host "  Logs:          $LogDir"
Write-Host "  Uninstall:     scripts\windows\uninstall-service.ps1"
Write-Host "  Do NOT delete \$LegacyInteractiveTask without David yes."
